### ISSUE TITLE
Failing LUT dropbox links

### ISSUE THREAD

**Issue by pratheekrebala** [pytroll/pyspectral#11]
Looks like the dropbox links for the Rayleigh look-up tables are broken: https://dl.dropboxusercontent.com/u/37482654/pyspectral/rayleigh_only/pyspectral_rayleigh_correction_luts.tgz

This is most likely happening due to Dropbox disabling Public Links - https://www.dropbox.com/help/files-folders/public-folder

It would be awesome if you are able to share the files on another location or if I can pull them from FTP.

Thanks for the awesome work with this project!

**Comment by adybbroe** [comment]
Dropbox links have been restored. Should be okay in the latest pypi release. Also, now in develop, all LUT tables and the rsr archive have been moved to Zenodo and links updated.
If you have time you are welcome testing @pratheekrebala !
So, remove your already downloaded LUTs locally and rerun. 
I expect to make a new release this week.

**Comment by adybbroe** [comment]
It is solved with the latest release 0.4.3

**Comment by pratheekrebala** [comment]
Hey @adybbroe - thanks for fixing this. I just tested this - it works perfectly!

**Comment by adybbroe** [comment]
Nice, I am glad to hear that!
