### ISSUE TITLE
AVHRR instrument naming - allow avhrr-#

### ISSUE THREAD

**Issue by adybbroe** [pytroll/pyspectral#127]
#### Code Sample, a minimal, complete, and verifiable piece of code

```python
# Your code here
from pyspectral.rsr_reader import RelativeSpectralResponse
avhrr3 = RelativeSpectralResponse('NOAA-19', 'avhrr-3')

```
#### Problem description

The above code sample gives a warning. The accepted naming of the sensor is `avhrr/3` and not `avhrr-3`. The former is how it is displayed on WMO Oscar, hence this is the accepted naming in Pyspectral.

It would be fair though to also accept `avhrr-3`. This is also what Satpy uses, as `/` can be problematic to handle in a yaml encoding for instance.

This means Satpy is always raising a warning here. Pyspectral anyhow fixes it so it reads the correct RSR data anyhow, so the warning in Satpy is most disturbing and confusing the user.

#### Versions of Python, package at hand and relevant dependencies

Python 3.8
Latest Pyspectral release: 0.10.2

Thank you for reporting an issue !

**Comment by djhoese** [comment]
I could see this being handled in two ways: pyspectral adds functionality for sensor "aliases" or satpy converts the sensor name before call pyspectral. I suppose doing the fix in pyspectral makes more sense long term.

**Comment by adybbroe** [comment]
> I could see this being handled in two ways: pyspectral adds functionality for sensor "aliases" or satpy converts the sensor name before call pyspectral. I suppose doing the fix in pyspectral makes more sense long term.

Yes, agree. I think in this case in particular it makes sense I would say, since slashes in names are awkward to handle in code
