### ISSUE TITLE
Implement RSRs for AGRI aboard FengYun-4B

### ISSUE THREAD

**Issue by simonrp84** [pytroll/pyspectral#143]
Fengyun-4B will soon be declared operational, and it'd be really nice to have the RSRs available in Pyspectral for the AGRI instrument - ready to go for when the data starts flowing.
This issue is a reminder to put in place these RSRs when possible.

**Comment by adybbroe** [comment]
@simonrp84 Tell me when you are ready or if you think I can do something here?

**Comment by adybbroe** [comment]
Closed by PR #171
