### ISSUE TITLE
Unit Convert Error in the Doc.

### ISSUE THREAD

**Issue by mqzhang1999** [pytroll/pyspectral#177]
#### Code Sample, a minimal, complete, and verifiable piece of code

```python
# Your code here

```
#### Problem description

On https://pyspectral.readthedocs.io/en/latest/api.html, the comment of the function pyspectral.blackbody.blackbody_wn, the unit convert "Converting from SI units to mW/m^2 sr^-1 (cm^-1)^-1: 1.0 W/m^2 sr^-1 (m^-1)^-1 = 0.1 mW/m^2 sr^-1 (cm^-1)^-1" is error . It should be 1E5, not 0.1.

#### Versions of Python, package at hand and relevant dependencies

Thank you for reporting an issue !

**Comment by adybbroe** [comment]
Thanks, you are absolutely right! Strange, since I thought we fixed this long time ago, it is correct a bit further up in the `planck` function so apparently we forgot to also update this. Thanks anyway.

**Comment by adybbroe** [comment]
Ah, now I see this should have been fixed in #117 but it wasn't.
