### ISSUE TITLE
Solar interpolation, straight wavelength bins

### ISSUE THREAD

**Issue by michaelaye** [pytroll/pyspectral#32]
In the solar.py code you have this for interpolation in the method `interpolate`:

```python
xspl = np.linspace(start, end, (end - start) / self._dlambda)
```

Could it be that you wanted:
```python
xspl = np.linspace(start, end, round((end - start) / self._dlambda)+1)
```
because then, for a dlambda=0.001, for example, you would actually get 1 nm wide bins.
The round is required because linspace takes an integer as input there, to avoid floating point issues?

With your method, `interpolate(dlambda=0.001, ival_wavelength=(0.200, 1.2))`
gets me this:
```python
array([0.2       , 0.201001  , 0.202002  , 0.203003  , 0.204004  ,
       0.20500501, 0.20600601, 0.20700701, 0.20800801, 0.20900901,
```
while I think the user expects bins of 1 nm in size at this point?
My solution would do exactly that.

Let me know, I can push another PR (but that, potentially, could change some numbers on your side).

**Comment by adybbroe** [comment]
Thanks, you are absolutely right, this is a bug. If you like please go ahead with the PR. 
It might affect some tests, It should at least. And if not, it indicates we need another unittest. Could be added to `test_solarflux.py`

**Comment by adybbroe** [comment]
I think I fixed this issue in develop now. Can you have a look @michaelaye ?

**Comment by adybbroe** [comment]
This issue should be solved by the above. No feedback from @michaelaye 
Issue being closed
