### ISSUE TITLE
No RSR data for Metop/AVHRR

### ISSUE THREAD

**Issue by pnuu** [pytroll/pyspectral#42]
#### Problem description
There is no RSR data available for Metop/AVHRR. Or at least they are not defined in the built-in configuration file.

**Comment by adybbroe** [comment]
In the RSR data that downloads automatically from Zenodo we have two files:
```
rsr_avhrr3_Metop-B.h5
rsr_avhrr3_Metop-A.h5
```

**Comment by adybbroe** [comment]
I have currently forgotten where I got the original response data. But they should not be needed!

**Comment by pnuu** [comment]
Oh, the config doesn't manage the RSRs already in the HDF5 files? Ok, I thought that all the files should be configured there so they are actually found by PySpectral.

**Comment by adybbroe** [comment]
No, exactly, the many satellite/platform specific entries in the config file is only for the case where you want to read the original response data, which will usually not be needed by the user. So, no worry, if a satellite is not listed there. The important thing is if there is a hdf5 file included in the files downloaded from Zenodo with responses for the platform.

**Comment by pnuu** [comment]
Ah, ok. And by setting `rsr_dir` and `rayleigh_dir` in `pyspectral.yaml` one can set the dir where the RSR and areosol files are stored, right?
