### ISSUE TITLE
'download_luts' and 'download_rsr' functions always download files

### ISSUE THREAD

**Issue by djhoese** [pytroll/pyspectral#75]
I'm using `pyspectral.utils.download_luts()` and `pyspectral.utils.download_rsr()` to pre-download the ancillary data needed by pyspectral. I noticed that it seems to re-download the data every time I run them. Is this expected? It is not a big deal for me since they should only be run once, but I was trying to run them to make sure I had the newest versions. If I have the newest versions I was hoping to not redownload.

**Comment by adybbroe** [comment]
Yes, as I said on slack this is as expected. I thought these functions and the two download scripts calling them were to be used only occasionally, and didn't think it was reasonable to build in the intelligence that it should check if the data locally were the latest already. But, I see the point, and think we should provide this to the users.
